services:
  auth-fe-mx:
    image: auth-fe-mx
    build:
      context: auth-fe-mx
      dockerfile: Dockerfile
    ports:
      - "5001:80"
  contact-fe-mx:
    image: contact-fe-mx
    build:
      context: contact-fe-mx
      dockerfile: Dockerfile
    ports:
      - "5002:80"
  auth-be-mx:
    image: auth-be-mx
    build:
      context: auth-be-mx
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./auth-be-mx/db.sqlite3:/app/db.sqlite3
  contact-be-mx:
    image: contact-be-mx
    build:
      context: contact-be-mx
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./contact-be-mx/db.sqlite3:/app/db.sqlite3
